export type StepContent = {
  title: string;
  meaning: string;
  expect: string;
  checklist: string[];
  pitfalls: string;
  tip: string;
};

export const stepContent: Record<string, Record<number, StepContent>> = {
  buyer: {
    1: {
      title: "Pre-Approval",
      meaning: "Getting pre-approved means a lender has reviewed your financial information and committed to lending you a specific amount for your home purchase. This is the crucial first step before looking at homes.",
      expect: "The lender will pull your credit score, ask for W-2s, pay stubs, bank statements, and tax returns. Expect this process to take 1–7 business days.",
      checklist: [
        "Gather last 2 years of tax returns",
        "Collect recent pay stubs (last 30 days)",
        "Gather bank statements (last 2–3 months)",
        "Review your credit report for errors at annualcreditreport.com",
        "Avoid making large purchases or opening new credit",
        "Shop at least 2–3 lenders to compare rates and fees",
      ],
      pitfalls: "Don't open new credit cards, buy a car, or make large purchases during this time — it can tank your credit score and debt-to-income ratio, jeopardizing your approval.",
      tip: "A pre-approval is very different from pre-qualification. Pre-approval means your information was actually verified. It carries far more weight with sellers — especially in competitive markets.",
    },
    2: {
      title: "House Hunting",
      meaning: "This is the search phase. You'll tour homes that fit your criteria and budget to find the one you want to buy. It's exciting, but requires discipline to stay aligned with your must-haves and financial limits.",
      expect: "You'll likely tour many homes. Some look better in photos than in person; others surprise you. In competitive markets, desirable homes move fast — sometimes receiving offers the first weekend. The average buyer tours 8–10 homes before making an offer.",
      checklist: [
        "Define your must-haves vs. nice-to-haves before you start",
        "Drive through neighborhoods at different times of day",
        "Take notes and photos at every showing",
        "Look past cosmetic issues (paint, carpet) — focus on layout and bones",
        "Check cell service, internet availability, and proximity to work",
        "Research school districts even if you don't have children (affects resale)",
        "Ask your agent about days on market and price history for any home you like",
      ],
      pitfalls: "Falling in love with a home outside your pre-approved budget, or getting 'buyer fatigue' and compromising on non-negotiables after too many showings.",
      tip: "Pay attention to the flow and natural light. You can repaint walls and replace flooring affordably. Moving walls and reconfiguring a floor plan costs tens of thousands.",
    },
    3: {
      title: "Making an Offer",
      meaning: "When you find the right home, your agent will help you draft a formal purchase agreement. This outlines the price you're offering, your proposed closing date, the amount of earnest money, and any contingencies that protect you.",
      expect: "You'll decide on a price (based on your agent's comparative market analysis), earnest money (typically 1–3% of the purchase price), and contingencies. The seller will accept, reject, or counter. Negotiations typically wrap up within 24–72 hours.",
      checklist: [
        "Review your agent's comparable sales (comps) carefully",
        "Decide on contingencies: financing, inspection, appraisal",
        "Determine earnest money amount (higher can make your offer stand out)",
        "Choose a closing date that works for you (typically 30–45 days out)",
        "Submit proof of pre-approval with your offer",
        "Understand the escalation clause option in competitive markets",
      ],
      pitfalls: "Waiving inspection or appraisal contingencies to win in a bidding war. These protect you from buying a money pit or overpaying. Only waive them if you fully understand the risk.",
      tip: "A clean offer with fewer contingencies is often more attractive to sellers than a higher price with many contingencies. Ask your agent what the sellers care about most — sometimes it's timeline, not just price.",
    },
    4: {
      title: "Home Inspection",
      meaning: "A licensed home inspector examines the property's condition from foundation to roof. This is your opportunity to learn everything about the home before you're legally committed to buying it.",
      expect: "Inspections typically take 2–4 hours. You'll receive a detailed written report covering hundreds of items. Almost every home has some issues — that's normal. After reviewing the report, you can request repairs, ask for a price reduction, or in some cases walk away.",
      checklist: [
        "Hire a licensed inspector (ask your agent for referrals, then verify credentials)",
        "Attend the inspection in person — you'll learn a lot just watching",
        "Take notes and photos in addition to the inspector's report",
        "Consider specialty inspections: sewer scope, radon, mold, chimney",
        "Prioritize safety issues and major systems (roof, HVAC, foundation, electrical)",
        "Submit repair requests within your contingency deadline",
      ],
      pitfalls: "Nitpicking minor cosmetic issues in your repair request. Focus on safety hazards and items that affect the home's major systems. Sellers are more likely to negotiate on significant issues than to fix scuffed baseboards.",
      tip: "The inspection report is your negotiating tool. Even in as-is sales, you typically have the right to inspect — you just may not be able to request repairs. A bad report can still give you grounds to exit the contract.",
    },
    5: {
      title: "Appraisal",
      meaning: "Your lender orders a professional appraisal to verify the home's market value. The lender will only finance up to the appraised value — so if you offered more than the home appraises for, you may need to renegotiate or make up the difference in cash.",
      expect: "An independent appraiser visits the property (usually a brief 30-minute walkthrough) and compares it to recent comparable sales. Expect the report within 1–2 weeks. Most appraisals come in at or near the purchase price, but gaps do happen — especially in hot markets.",
      checklist: [
        "Your lender will order the appraisal — you don't select the appraiser",
        "Ensure the seller keeps the home in showing condition for the visit",
        "Review the appraisal report when it arrives",
        "If appraisal comes in low, negotiate with seller, make up the gap in cash, or invoke the appraisal contingency to exit",
        "Ask your agent for comparables (comps) used to see if you can contest a low appraisal",
      ],
      pitfalls: "Assuming the appraisal is automatically on your side. Appraisers work for the lender, not you. If the home appraises low and you have no contingency, you're stuck either paying the gap or losing your earnest money.",
      tip: "In a very competitive market, sellers sometimes request that buyers waive the appraisal contingency. Only do this if you can genuinely afford to cover the gap in cash and you've done your own research on comparables.",
    },
    6: {
      title: "Final Loan Approval",
      meaning: "Your loan goes through final underwriting — the lender's detailed review of everything. They'll issue a \"Clear to Close\" (CTC) once all conditions are satisfied. This is the last major hurdle before closing.",
      expect: "Underwriters will verify every document submitted during pre-approval. They may ask for updated bank statements, letters of explanation, or additional documentation. Expect the process to take 1–3 weeks after the appraisal is complete.",
      checklist: [
        "Respond to any lender requests for documents within 24 hours",
        "Do not change jobs or switch employers during this period",
        "Do not make any large deposits without documented source",
        "Do not apply for new credit of any kind",
        "Maintain your current bank balances",
        "Schedule your final walk-through for the day before or morning of closing",
        "Review your Closing Disclosure (CD) carefully when received — you must get it 3 business days before closing",
      ],
      pitfalls: "Changing jobs, making large purchases, or opening new credit accounts right before closing. Even after a CTC, lenders may do a final credit pull. One big change can collapse the deal days before you're supposed to get the keys.",
      tip: "Your Closing Disclosure will show every dollar you need to bring to closing. Compare it to your Loan Estimate — any significant changes should be questioned with your lender immediately.",
    },
    7: {
      title: "Closing Day",
      meaning: "The final day of your home purchase. You'll sign a large stack of documents, pay your closing costs and down payment, and legally take ownership. By the end of the day, you'll have keys.",
      expect: "Closing typically takes 1–2 hours. You'll sign the mortgage note, deed of trust, and many other documents. You'll need to bring a cashier's check or wire transfer for closing costs and down payment. Your lender and title company will coordinate the process.",
      checklist: [
        "Complete your final walk-through to verify the home's condition",
        "Bring government-issued photo ID",
        "Verify wire instructions by phone (NEVER trust email alone — see fraud warning)",
        "Bring cashier's check or confirm wire transfer is completed",
        "Review and understand every document before you sign",
        "Confirm closing time and location with your agent and title company",
        "Bring your checkbook for any small last-minute adjustments",
      ],
      pitfalls: "Wire fraud is rampant in real estate. Criminals intercept emails and send fake wiring instructions. Always call the title company at a number you found independently to verify instructions — before wiring any money.",
      tip: "Don't schedule movers for the morning of closing — delays happen. Give yourself at least a half day buffer. Also, homeowner's insurance must be in effect before you can close.",
    },
    8: {
      title: "Moving In",
      meaning: "You've closed — now it's time to take possession and begin your new chapter. The logistics of moving can be overwhelming, but with a good plan, the transition goes smoothly.",
      expect: "You'll coordinate movers, transfer utilities, update your address everywhere, and start getting comfortable in your new home. Plan for the first week to be a bit chaotic as you unpack and figure out where everything lives.",
      checklist: [
        "Change the locks on all exterior doors immediately",
        "Transfer utilities to your name (electric, gas, water, internet)",
        "Update your address: USPS, employer, bank, DMV, IRS",
        "Locate your home's main water shut-off, electrical panel, and gas shut-off",
        "Test all smoke detectors and carbon monoxide alarms",
        "Review home warranty coverage if applicable",
        "Introduce yourself to neighbors — they can be valuable resources",
      ],
      pitfalls: "Forgetting to change the locks. Previous owners, contractors, and real estate agents may all have copies of keys you don't know about.",
      tip: "Pack a 'first night box' with essentials you'll need immediately: toiletries, a change of clothes, phone chargers, important documents, and snacks. It saves you from digging through 40 boxes to find your toothbrush.",
    },
  },
  seller: {
    1: {
      title: "Preparing Your Home",
      meaning: "Before you list, you need to prepare your home to show at its absolute best. The work you put in here directly translates to a higher sale price and faster sale. First impressions set the tone for every showing.",
      expect: "Plan for 1–4 weeks of preparation depending on your home's current condition. Deep cleaning, decluttering, minor repairs, and possibly light staging. If your home needs more significant work, discuss with your agent whether the ROI justifies the timeline.",
      checklist: [
        "Declutter every room, closet, garage, and basement",
        "Deep clean from ceiling fans down to baseboards",
        "Depersonalize — remove family photos and personal items",
        "Complete minor repairs: dripping faucets, scuffed walls, broken fixtures",
        "Touch up paint with neutral colors in any room that needs it",
        "Enhance curb appeal: fresh mulch, trimmed landscaping, clean walkways",
        "Consider professional staging consultation (even a 2-hour consult can transform your approach)",
        "Pre-inspect your own home to avoid surprises during buyer's inspection",
      ],
      pitfalls: "Taking buyer feedback personally. When you decide to sell, the home becomes a product, not your personal sanctuary. Buyers need to envision themselves living there — not you.",
      tip: "A good rule of thumb: every dollar spent on professional staging returns $2–3 at sale. At minimum, ensure the home is immaculate and that furniture arrangement makes rooms feel as large as possible.",
    },
    2: {
      title: "Setting the Price",
      meaning: "Pricing is the single most important decision of your sale. Too high and you'll sit on the market, causing buyers to wonder what's wrong. Too low and you leave money on the table. The right price attracts competition.",
      expect: "Your agent will prepare a Comparative Market Analysis (CMA) showing what similar homes sold for recently in your area. Pricing well means landing in a range that attracts multiple buyers — which can actually result in a higher final price through competition.",
      checklist: [
        "Review your agent's CMA carefully — ask questions about every comparable",
        "Understand your local market: buyer's market (high inventory) vs. seller's market (low inventory)",
        "Consider your timeline — need to sell quickly means pricing more aggressively",
        "Factor in any major repairs or updates you've done",
        "Ask about the \"price bracket\" effect online (buyers filter by round numbers)",
        "Agree on a price reduction strategy before listing — when will you drop, and by how much?",
      ],
      pitfalls: "Overpricing due to emotional attachment to your home. A home that sits on the market for weeks loses its appeal — buyers assume something is wrong with it. The first 2 weeks on market are your most valuable window.",
      tip: "Pricing slightly below a round number (e.g., $499,000 instead of $500,000) can significantly expand your buyer pool by appearing in more online search filter results.",
    },
    3: {
      title: "Listing Your Home",
      meaning: "Going live on the market means your home is available for the world to see and schedule showings. The quality of your listing — especially the photos — directly impacts how many buyers come through the door.",
      expect: "Your agent will coordinate professional photography (standard), write your listing description, and submit to the MLS. You may also see a lockbox installed, a yard sign placed, and your home syndicated to Zillow, Realtor.com, and other sites within 24–48 hours of going live.",
      checklist: [
        "Review and approve all listing photos before they go live",
        "Read and approve the listing description for accuracy",
        "Confirm your home is in pristine condition for the first showing day",
        "Secure valuables and medications before showings begin",
        "Understand your agent's showing scheduling system (app vs. phone)",
        "Plan where you'll go during showings — buyers are most comfortable without sellers present",
        "Ask about a coming soon strategy to build early interest",
      ],
      pitfalls: "Allowing low-quality or too-few photos. The first showing is online — buyers decide whether to visit based entirely on photos. Dark, cluttered, or poorly-staged photos are a direct revenue killer.",
      tip: "Consider listing on a Thursday or Friday — homes listed later in the week have the freshest status when buyers are planning weekend showings, which is when most people tour homes.",
    },
    4: {
      title: "Showings & Open Houses",
      meaning: "Buyers need to experience your home in person. This phase requires flexibility on your end — accommodating showings on buyers' schedules — and keeping the home in constant showing-ready condition.",
      expect: "You'll likely have showings scheduled with 30 minutes to a few hours' notice. Keep the home clean, lights on, and temperature comfortable. You will leave for every showing. Open houses typically happen the first weekend and may be repeated if activity slows.",
      checklist: [
        "Secure all valuables, prescription medications, and financial documents",
        "Create a 'showing ready' routine: make beds, wipe down surfaces, take out trash",
        "Turn on all lights before leaving for showings",
        "Set a comfortable temperature",
        "Remove pets or make arrangements for them during showings",
        "Leave quickly — don't let buyers see you",
        "Follow up with your agent for feedback after each showing",
      ],
      pitfalls: "Hovering during showings or being present for open houses. Buyers are reluctant to open closets, spend time in rooms, or speak freely when the seller is present. It creates discomfort that translates directly to lower offers.",
      tip: "A subtle, pleasant scent (fresh flowers, light citrus) can create a positive emotional response. Avoid strong candles or air fresheners — they make buyers wonder what you're masking.",
    },
    5: {
      title: "Reviewing Offers",
      meaning: "When offers come in, you'll evaluate each one with your agent and decide whether to accept, reject, or counter. The best offer isn't always the highest price — the overall terms matter enormously.",
      expect: "In a seller's market, you may receive multiple offers quickly — sometimes within hours of listing. In slower markets, offers may take days or weeks. Your agent will present all offers and prepare a net sheet showing what you'll actually receive from each.",
      checklist: [
        "Compare net proceeds across all offers (price minus concessions minus estimated closing costs)",
        "Evaluate buyer financing: cash offers close faster and are most reliable; FHA/VA loans have additional requirements",
        "Review down payment size (larger down = stronger buyer)",
        "Count contingencies: fewer contingencies reduce risk of the deal falling through",
        "Check proposed closing date against your needs",
        "Consider requesting highest-and-best offers if you have multiple",
        "Understand your right to counter — you don't have to accept anything as-is",
      ],
      pitfalls: "Choosing the highest price offer without reading the fine print. A $10,000 higher offer with a financing contingency, low earnest money, and a request for $5,000 in seller concessions may net you less than a cleaner lower offer.",
      tip: "A solid offer from a well-qualified buyer with conventional financing and a strong down payment is often worth more than a higher number from a riskier buyer. Ask your agent to rank offers by likelihood of closing, not just price.",
    },
    6: {
      title: "Under Contract",
      meaning: "A buyer has accepted your agreed terms and both parties have signed the purchase agreement. You are not sold yet — the buyer will now conduct inspections, get an appraisal, and finalize their financing. Most deals close, but this period has the most potential for complications.",
      expect: "Inspections typically happen within 1–2 weeks of going under contract. You'll likely receive a repair request or negotiation. Then the buyer's appraisal (ordered by their lender) occurs. Throughout, your buyer's lender is processing the loan. Timeline to closing is typically 30–45 days.",
      checklist: [
        "Keep the home available and accessible for inspector and appraiser",
        "Maintain the home's condition throughout — the buyer has a right to a final walk-through",
        "Continue maintaining systems and appliances",
        "Respond promptly to repair requests — delays can cost you the deal",
        "Avoid making major changes to the property",
        "Start planning your own move-out and next steps",
        "Don't cancel your homeowner's insurance until after closing",
      ],
      pitfalls: "Being inflexible on reasonable repair requests. Buyers may feel entitled to request everything; sellers don't have to agree to everything. But a good-faith response on safety items or major systems keeps deals together.",
      tip: "Sometimes it's smarter to offer a closing cost credit instead of completing repairs yourself. The buyer gets flexibility to hire their own contractors, and you don't have to manage repair work while also preparing to move.",
    },
    7: {
      title: "Final Steps",
      meaning: "The finish line is in sight. The buyer has received their Clear to Close, and both parties are preparing for the transfer of ownership. Your job now is to prepare to hand over the home in the agreed-upon condition.",
      expect: "You'll coordinate your move-out, ensure all agreed-upon items are completed, and prepare to transfer utilities and keys. The buyer will conduct a final walk-through, typically the day before or morning of closing.",
      checklist: [
        "Complete all agreed-upon repairs with licensed contractors and keep receipts",
        "Ensure all appliances and systems that convey are in working order",
        "Remove all personal property not included in the sale",
        "Do not take anything that is attached to the home unless specified in writing",
        "Leave the home broom-clean or better",
        "Leave appliance manuals, warranty documents, and extra keys",
        "Cancel utilities effective the day of closing",
        "Confirm final closing time and location",
      ],
      pitfalls: "Removing fixtures, light fixtures, or appliances that weren't excluded in the contract. What's attached to the house generally conveys with the sale. This can become a legal issue if buyers notice during the final walk-through.",
      tip: "Leave a note for the new owners with helpful information: wifi passwords, trash pickup days, favorite neighborhood spots, and contact info for your best local service providers. It's a gracious gesture that costs nothing.",
    },
    8: {
      title: "Closing Day",
      meaning: "The day of settlement — ownership formally transfers from you to the buyer. You'll sign documents, the title company will distribute funds, and you'll hand over the keys. The proceeds will arrive in your account, typically the same day or the next business day.",
      expect: "Sellers often don't need to attend closing in person — many states allow remote or pre-signing. Closing typically takes 30–60 minutes for sellers (less than buyers). Your proceeds will be distributed after all payoffs (mortgage, liens, fees) are deducted.",
      checklist: [
        "Bring government-issued photo ID",
        "Confirm all agreed-upon items are complete",
        "Bring all keys, garage door openers, mailbox keys, and access codes",
        "Ensure the home is in the agreed condition before the final walk-through",
        "Confirm how and when proceeds will be disbursed",
        "Plan to have homeowner's insurance remain active until proceeds clear",
        "Celebrate — you've done it",
      ],
      pitfalls: "Canceling your homeowner's insurance too early. If something happens between the final walk-through and the actual title transfer, you could be exposed. Keep it active until closing is confirmed complete.",
      tip: "After closing, update your records for tax purposes. You may be able to exclude up to $250,000 ($500,000 if married) of capital gains on the sale of a primary residence if you've lived there at least 2 of the last 5 years. Consult a tax professional.",
    },
  },
  both: {
    1: {
      title: "Get Pre-Approved",
      meaning: "The very first step when buying and selling simultaneously is to understand your purchasing power. Your pre-approval tells you how much home you can buy — and critically, whether you can carry two mortgages temporarily if needed, or whether your purchase is fully dependent on your sale closing first.",
      expect: "A lender will review your credit, income, debts, and assets. Be upfront that you're also selling a home — this affects your debt-to-income calculation and your lender's strategy. Expect 1–7 business days. You'll want to ask specifically about bridge loan options.",
      checklist: [
        "Gather last 2 years of tax returns and W-2s",
        "Collect recent pay stubs and bank statements",
        "Ask your lender about bridge loans — short-term financing that covers the gap between buying and selling",
        "Ask whether your purchase contract can include a 'contingent on sale' clause",
        "Get pre-approved for your target purchase price range",
        "Discuss whether you can afford to carry both mortgages temporarily if closings don't align",
        "Shop at least 2–3 lenders to compare rates",
      ],
      pitfalls: "Assuming your pre-approval from years ago still applies — or not telling your lender you're also selling. Your current equity and the terms of your sale significantly affect your buying capacity.",
      tip: "A 'bridge loan' allows you to tap your current home's equity to fund the purchase of your new home before your sale closes. Not all lenders offer them and they carry costs, but they can eliminate the pressure of synchronized closings.",
    },
    2: {
      title: "Assess Your Home's Value",
      meaning: "Before you start shopping aggressively for your next home, you need a realistic picture of what your current home will sell for — and what you'll net after paying off your mortgage and closing costs. This number is your 'war chest' for the next purchase.",
      expect: "Your agent will prepare a Comparative Market Analysis (CMA) showing recent comparable sales in your area. This gives you a realistic price range — not your Zillow estimate, which can be 5–15% off. Your net proceeds estimate tells you exactly what you'll have to work with.",
      checklist: [
        "Request a CMA from your agent (or two agents for a second opinion)",
        "Ask for a seller's net sheet projecting your proceeds at different sale prices",
        "Get a sense of your mortgage payoff amount from your lender's website",
        "Factor in selling costs: agent commissions, closing costs, any repairs",
        "Use the Seller Net Sheet calculator in the Calculators section of this app",
        "Understand whether your equity can cover your down payment on the next home",
      ],
      pitfalls: "Using your Zillow Zestimate as your planning number. Automated estimates are notoriously inaccurate — sometimes by $30,000–$80,000 in either direction. Only a licensed agent's CMA based on actual recent sales gives you a reliable number.",
      tip: "In a strong seller's market, consider whether to sell first (safe but stressful if you need somewhere to go) or buy first (risky if your sale falls through, but avoids the temporary housing scramble). Your agent and lender can help you decide based on your financial cushion.",
    },
    3: {
      title: "Prepare & List Your Home",
      meaning: "Getting your home on the market is often the highest-leverage move in the buy-sell process. Once your home is listed and active, you have much more leverage as a buyer — agents and sellers take contingent offers more seriously when the home is already under contract or listed.",
      expect: "Preparation takes 1–4 weeks. After listing, you'll typically start receiving showing requests within days in an active market. Your goal is to get your home under contract as quickly as possible so you can pursue your next home with more certainty.",
      checklist: [
        "Declutter, deep clean, and complete minor repairs",
        "Hire a professional photographer — this is non-negotiable",
        "Consider timing: consult your agent about the best time to list in your market",
        "Discuss with your agent how to handle a 'contingent on purchase' scenario",
        "Set up a showing system that works around your schedule",
        "Consider a rent-back clause in your sale — this lets you stay in your home for 30–60 days after closing, giving you time to close on your purchase",
      ],
      pitfalls: "Listing before you're truly ready to show. A rushed listing with poor photos or a messy home creates a weak first impression that's difficult to recover from. Take the extra week to prepare.",
      tip: "A 'rent-back' or 'leaseback' arrangement is one of the most powerful tools for simultaneous buyers/sellers. You close the sale on time (giving the buyer their home), but you pay rent to stay in the house for up to 60 days while you close on your purchase. Many buyers will agree to this in exchange for a smoother transaction.",
    },
    4: {
      title: "Start House Hunting",
      meaning: "With your pre-approval in hand and your home listed, you're in a much stronger position to shop for your next home. You don't have to have your current home under contract before looking — but you should be actively listing and showing it.",
      expect: "You'll tour homes that fit your criteria and budget. Communicate clearly with your agent about your timeline and the status of your current home's sale. When you find a home you love, your offer strategy will depend on where your sale stands.",
      checklist: [
        "Define your must-haves and budget for the new home",
        "Work with an agent in the new area (or your current agent if buying nearby)",
        "Attend open houses and private showings",
        "Track market timing: how fast are homes moving in your target area?",
        "Be ready to move quickly when you find the right property",
        "Note that some sellers won't accept contingent offers — be prepared to discuss options with your agent",
      ],
      pitfalls: "Falling in love with a home you can't make a competitive offer on because your home isn't yet under contract. Keep your heart attached loosely — your situation changes rapidly once your home goes under contract.",
      tip: "Share your situation openly with your agent. If a seller knows you're well-prepared — pre-approved, home listed, serious about the timeline — they may be more flexible about a contingent offer than you'd expect.",
    },
    5: {
      title: "Receive & Review Offers on Your Sale",
      meaning: "When offers come in on your home, your evaluation should be shaped by your buying situation. Beyond price and terms, consider the proposed closing date — does it align with when you can realistically close on your purchase? Flexibility here is worth real money.",
      expect: "You'll review offers with your agent and assess net proceeds, buyer qualification, contingencies, and proposed closing date. Counter-offers are normal. Your goal is to lock in a contract with terms that give you breathing room to also close your purchase.",
      checklist: [
        "Review all offers for price, contingencies, buyer financing, and closing date",
        "Ask for a seller's net sheet for each offer",
        "Prioritize buyers with fewer contingencies and stronger financing",
        "Negotiate a closing date that aligns with your purchase timeline (45–60 days often works well)",
        "Consider asking for a rent-back clause if you need more time",
        "Once you accept an offer, notify your buyer's agent immediately so you can write your offer on the new home",
      ],
      pitfalls: "Accepting an offer with a very short closing timeline (21–30 days) without confirming you can close on your purchase in time. Closing gaps cause significant stress and can force you into temporary housing.",
      tip: "If your home receives multiple offers, use the competition to negotiate the best closing date for you — not just the highest price. The winning buyer who also agrees to a 50-day close (plus rent-back if needed) may be your best overall offer.",
    },
    6: {
      title: "Make an Offer on Your New Home",
      meaning: "With your home under contract or in a strong position, you're now ready to make a serious offer on your next home. Your agent will help you structure an offer that's competitive given your situation — which may or may not include a sale contingency.",
      expect: "If your home is already under contract with a solid buyer, many sellers will accept a purchase contingency (your purchase is contingent on your sale closing). If your home is merely listed, contingent offers are harder. Your offer will reflect price, earnest money, contingencies, and a proposed closing date.",
      checklist: [
        "Update your lender on the status of your current home's sale",
        "Get your agent's read on whether a contingent offer is realistic in this seller's market",
        "Determine your offer price based on comps",
        "Align your proposed closing date with your sale's closing date (typically same day or 1–3 days later)",
        "Include your financing, inspection, and appraisal contingencies",
        "Submit a strong earnest money deposit to demonstrate seriousness",
      ],
      pitfalls: "Making a non-contingent offer to be competitive when you actually need the sale proceeds to close. This is a serious financial risk. Make sure you have the cushion (bridge loan or other funds) to follow through without your sale closing first.",
      tip: "Ask your agent to call the listing agent before submitting your offer and explain your situation — that your home is under contract, your buyer is well-qualified, and the timelines align. Personal outreach from agent to agent can make sellers much more receptive to a contingent offer.",
    },
    7: {
      title: "Coordinate Contracts & Timelines",
      meaning: "You're now under contract on both sides — selling your old home and buying your new one. This is the most logistically complex phase. The goal is to ensure both closings happen smoothly, ideally with your sale closing first (or same day) so your proceeds are available for your purchase.",
      expect: "You'll be managing two sets of deadlines simultaneously: inspections, appraisals, loan approvals, and closing dates on both transactions. Your agent and attorney/title company should be tracking all deadlines. Communication between all parties is critical.",
      checklist: [
        "Create a master timeline with all deadlines from both contracts",
        "Ensure your sale closing date is the same day or 1–3 days before your purchase closing",
        "Confirm both lenders and title companies are aware of the dual transaction",
        "Ask your real estate attorney or title company if the proceeds from your sale can be 'same-day transferred' to your purchase",
        "Have a contingency plan if either transaction hits a delay",
        "Discuss temporary housing options in case closings slip",
        "Keep both agents in close communication with each other",
      ],
      pitfalls: "Scheduling your purchase closing before your sale closes, without alternative funds to cover the down payment. If your sale is delayed by even a day, your purchase can fall through — and you could lose your earnest money.",
      tip: "Many experienced agents and title companies handle 'double closings' where a sale and purchase close the same day, often with the title company coordinating the funds from the sale to the purchase. Ask both of your title companies if they can coordinate.",
    },
    8: {
      title: "Inspections on Both Homes",
      meaning: "While inspections on your purchase are standard, you should also be prepared for the inspection your buyer will conduct on your current home. You're simultaneously a buyer scrutinizing a new home and a seller receiving scrutiny on your old one.",
      expect: "Both inspections will happen within 1–2 weeks of each contract's execution. Expect 2–4 hours each. Your buyer's inspection may result in a repair request; your own inspection will identify issues to negotiate with the seller of your new home.",
      checklist: [
        "Hire a licensed inspector for your purchase — attend in person",
        "Prepare your home for your buyer's inspector: all utilities on, clear access to attic/crawl space/panel",
        "Complete any agreed-upon repairs on your current home promptly",
        "Prioritize safety and major system issues in your purchase inspection report",
        "Consider specialty inspections on your new home: sewer scope, radon, mold",
        "Respond to your buyer's repair requests quickly to keep the sale on track",
      ],
      pitfalls: "Letting inspection negotiations on your sale derail your focus on your purchase — or vice versa. Both need attention simultaneously. Stay organized and let your agents handle the negotiation coordination where possible.",
      tip: "Consider having your own home pre-inspected before listing. It eliminates surprises when your buyer's inspector comes through and lets you address issues on your terms and timeline instead of under contract pressure.",
    },
    9: {
      title: "Appraisals & Final Loan Approvals",
      meaning: "Both transactions are now heading toward their respective closings. Your lender for your purchase will order an appraisal; your buyer's lender will appraise your current home. Both need to come in at or above the contracted price for the deals to close as written.",
      expect: "Appraisals are typically ordered 1–2 weeks after contracts are executed and take another 1–2 weeks to complete. Simultaneously, both you and your buyer are completing final underwriting. This is a waiting period — stay available, respond quickly to any document requests.",
      checklist: [
        "Ensure your current home is in good condition for your buyer's appraiser",
        "Respond to all lender document requests within 24 hours",
        "Maintain financial stability: no new credit, no large purchases, no job changes",
        "If either appraisal comes in low, work with your agent to renegotiate",
        "Track both closing timelines to confirm they're still aligned",
        "Get your Closing Disclosures reviewed as soon as they arrive (required 3 business days before closing)",
      ],
      pitfalls: "Assuming both transactions will glide to close without hiccups. Appraisals can come in low, lenders can ask for last-minute documentation, and any delay in one transaction can ripple to the other. Build buffer into your timeline.",
      tip: "Ask both agents to check in with their respective title companies weekly to confirm no open title issues, HOA document delays, or payoff requests are holding things up. Most closing delays are caused by overlooked administrative issues, not major problems.",
    },
    10: {
      title: "Pre-Closing Preparation",
      meaning: "The finish line is close. Both transactions are targeting their closing dates. Your job now is to prepare for the move — coordinating logistics, arranging movers, and ensuring both properties are in the agreed-upon condition for their respective closings.",
      expect: "The week before closing will be busy: final walk-throughs on both homes, movers to coordinate, utilities to transfer, and documents to review. Make sure you know where you're going and when — especially if both closings are happening the same day.",
      checklist: [
        "Schedule movers for after both closings are confirmed",
        "Schedule your final walk-through on your purchase for the day before or morning of closing",
        "Ensure your current home is vacated and in broom-clean condition by agreed date",
        "Complete all repairs on your current home — your buyer will walk through",
        "Review both Closing Disclosures when they arrive",
        "Confirm wire transfer amounts and verify wire instructions by phone for both transactions",
        "Arrange for key handoff on both homes",
      ],
      pitfalls: "Scheduling movers before closings are confirmed. Closing delays are common, and moving companies won't refund last-minute cancellations. Book movers for the afternoon of closing day or the day after.",
      tip: "If your closings are the same day, try to close your sale in the morning and your purchase in the afternoon. That gives the title company time to transfer your proceeds and ensures you're not caught in a timing bind.",
    },
    11: {
      title: "Closing Day — Selling Your Home",
      meaning: "Today you officially transfer ownership of your current home to the buyer and receive your net proceeds. This money will fund your purchase — either already wired to the title company for your purchase or arriving in your account to be forwarded.",
      expect: "Sellers' closings are typically brief — 30–60 minutes. You may not need to attend in person depending on your state. You'll receive your proceeds either by wire (same day) or check. Confirm with both title companies that funds can be transferred for your purchase.",
      checklist: [
        "Bring government-issued photo ID",
        "Bring all keys, garage openers, mailbox keys, and gate codes",
        "Confirm the home is vacant and in agreed condition",
        "Verify wire instructions for your proceeds by phone",
        "Confirm proceeds will be available for your purchase (same-day or next-day)",
        "Cancel homeowner's insurance after closing is confirmed",
        "Update your lender on your buyer's side that the sale has closed",
      ],
      pitfalls: "Assuming your sale closing automatically funds your purchase. Title companies need to coordinate the transfer. Confirm in advance that the timing and mechanics are arranged between both title companies.",
      tip: "Once your sale closes, let yourself feel the relief — but stay focused. Your purchase closing is happening today or in the next few days. The celebration comes after you have keys to the new home.",
    },
    12: {
      title: "Closing Day — Buying Your New Home",
      meaning: "The final step of your combined journey. Today you sign the mortgage documents, pay any remaining closing costs, and receive the keys to your new home. After everything you've managed to coordinate, this moment is well-earned.",
      expect: "Buyer closings take 1–2 hours. You'll sign the mortgage note, deed of trust, and numerous other documents. Your down payment and closing costs (partially funded by your sale proceeds) will be required. After signing, the deed is recorded and the home is yours.",
      checklist: [
        "Bring government-issued photo ID",
        "Confirm down payment and closing cost funds are available",
        "Verify wire instructions by phone — never trust email alone",
        "Complete your final walk-through on the new home before closing",
        "Review all documents before signing — ask questions",
        "Confirm key handoff time and procedure",
        "Change locks on the new home as soon as you're inside",
        "Transfer utilities and update address everywhere",
      ],
      pitfalls: "Skipping the final walk-through. Between the time you last saw the home and closing, things can change. It's your last opportunity to confirm the home is in the agreed condition before you sign.",
      tip: "Congratulations — you've successfully navigated one of the most complex logistics challenges in personal finance: selling one home and buying another simultaneously. Most people do it only once or twice in their lives. You've earned those keys.",
    },
  },
};
